logging:
  level: INFO
  format: '%(asctime)s (%(name)s) [%(levelname)s] %(message)s'
  datefmt: '%H:%M:%S %d-%m-%Y'

server:
  server_host: "127.0.0.1"
  server_port: 8000
  show_last_messages_count: 3
  message_lifetime_seconds: 3
  user_message_limit: 5
  chating_block_lifetime_seconds: 5
  max_reports_count: 1
  ban_lifetime_seconds: 3